apiVersion: v1
kind: Service
metadata:
  name: wf-3
  namespace: test-add
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: wf-3
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080